### PR TITLE
Removing completely the native levelup plugin as now it rely all on the core plugin  

### PR DESCRIPTION
**Pull request by 00christian00**
Hello,
I removed all references to the native soomla levelup plugin since now it is bypassed by relying directly on the keyvaluestorage of the core plugin.
Now you have 1:1 correspondence between the editor and the device, minus the encryption.

Added some functions to levelup to make it easier to create levels.
Made rewards optional for the missions.

### CODE REVIEW

**Comment by borisspektor** [comment]
@00christian00 thank you for your contribution. However, we need the calls to the native plugin as there's logic in there as well, not just storage methods.

**Comment by 00christian00** [comment]
Hi,
Can you tell me what additional logic is in the native plugin? I haven't found anything.

**Comment by borisspektor** [comment]
Besides saving the data we also send events there. The order of operations matters, and applies also for Cocos2d-x, so we would like to have a single place to change this.
Why do you need this change?

**Comment by 00christian00** [comment]
Having everything on the Unity side means that everything you see on the editor is what you will get on the final product.
Having two separate codes doing the same thing is bad, it mean you could have a bug on either one of them and then it will be hell to find what's happening.
From what I saw, the whole thing is replicated on the unity side including events.

**Comment by borisspektor** [comment]
@00christian00 we also have cocos2d-x using those libs. Thank you for your feedback. I'll add a ticket to consider what you wrote.

**Comment by dimat** [comment]
This change would make a lot of sense. I have also experienced difference in behaviour between Unity Editor implementation and native implementations. Most of the time I was testing my game in Unity, and when I built a native version, nothing has worked at all.

If there is only one implementation of ScoreStorage, LevelStorage and GateStorage, then it'll be much easier to maintain consistent behaviour by having code in only one singe place. Also, native implementations also use KeyValueStorage underneath, so the end result doesn't change at all and it doesn't compromise security neither.

**Comment by 00christian00** [comment]
So, now that Level up is semi-abandoned on Unity, why not integrate my patch so that it will be easier to support?
Another benefit of not having to rely on the plugin is that it could be used also on platform where the core plugin is not working or not implemented(Apple TV for example), by simply switching to PlayerPrefs.

**Pull request closed without merging**
